version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      # n8n core
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password

      # Database (Postgres)
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n_password
      - NODE_FUNCTION_ALLOW_EXTERNAL=pg

      # n8n port
      - N8N_PORT=5555

      # Production URL / OAuth redirect overrides
      - N8N_PROTOCOL=https
      - N8N_HOST=n8n-railway-production-a11a.up.railway.app
      - N8N_EDITOR_BASE_URL=https://n8n-railway-production-a11a.up.railway.app
      - WEBHOOK_URL=https://n8n-railway-production-a11a.up.railway.app
      - N8N_WEBHOOK_TUNNEL_URL=https://n8n-railway-production-a11a.up.railway.app

    ports:
      - "5555:5555"
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
